language: go

go:
  - "1.8"
  - "1.9"
  - "1.10"
  - "1.11"
  - "1.12"

install:
  - export PATH=$PATH:$HOME/gopath/bin
  - go get github.com/stretchr/testify/assert

script:
  - go build
#  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash) -t eb2ffadc-95db-430a-b4ad-1cdaac1fcbcd